version: '3.8'
services:
  app-staging:
    build: .
    container_name: staging-esg
    ports:
      - "8081:8080"
  app-prod:
    build: .
    container_name: prod-esg
    ports:
      - "8080:8080"